name: Publish Website
on: push
jobs:
  build-project:
    name: Build project
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install bundle
      run: bundle install
    - name: Upload static site content
      uses: actions/upload-artifact@v3
      with:
        name: assets
        path: assets/